### ISSUE TITLE
Appeal approval outside Guardian

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#217]
**Summary**
Complex appeal approval flow can't be modelled using policy config YAML file so in that case, Guardian should be able to integrate with existing complex approval flow like `bpmn`.

**Proposed solution**
Guardian can integrate with exiting approval flow either by webhook or subscribe to events.

**Comment by rahmatrhd** [comment]
my rough thought for now is, we can introduce `type` field in the approval step configuration. If the approach for this is to fetch to external service, we can set the type as `fetch` and provide the host, creds, payload etc. While the existing human/auto approval step would be the `normal` type

**Comment by ravisuhag** [comment]
Hmm. This is interesting. I can think of couple of types.

**Comment by rahmatrhd** [comment]
pardon me, I just realized that we already have `strategy` field with possible values `auto` and `manual`, we can simply introduce `http` for this 😁

**Comment by rahmatrhd** [comment]
my proposal for this:
```yaml
# policy
id: my-policy
steps:
- name: owner-approval
  strategy: manual
  approvers:
  - $appeal.resource.details.owner
- name: external-approval
  strategy: auto
  http:
    url: http://example.com/approval/$appeal.account_id
    authorization:
      type: basic
      username: user
      password: pass
  approve_if: '$response.status == 200 && $response.body.foo == "bar"' 
```
1. no direct API contract with guardian
2. can just use existing `auto` strategy with the same resolution using existing `approve_if`. Only needs to add `$response` params if `http` config presents
3. one field addition which is `http` containing target API info
