### ISSUE TITLE
Able to register gcp iam roles as resources

### ISSUE THREAD

**Issue by utsav-agarwal** [odpf/guardian#218]
**Summary**
Right now, To Get the access to a Particular role, the code is been  added in terracode for it.
We trying to solve it through guardian by exposing project roles as the guardian resources and thus requesting access through console by hitting Guardian api's

**Proposed solution**
Adding Provider config in config store having resources list as the Iam roles and thus calling GCP Project roles api , filtering out the roles mentioned in provider resource list. 

@singhvikash11 @bsushmith

**Comment by rahmatrhd** [comment]
the current [gcloud_iam provider](https://odpf.github.io/guardian/docs/providers/gcloud_iam) already solves this use case. Users can select a resource that is a gcp project and a role (fetched from gcp iam roles). The only missing part right now is for filtering the roles which also already raised here https://github.com/odpf/guardian/issues/184

**Comment by utsav14nov** [comment]
@rahmatrhd 
We are categorising roles by business use cases which can de decided.
There can be these category types and each will have the roles assigned to it.

Following is the sample policy

```
type: gcloud_iam
urn: g-gopay-data-access
credentials:
  service_account_key: secret_key
  resource_name: projects/g-gopay-data-access
appeal:
  allow_permanent_access: true
  allow_active_access_extension_in: 24h
resources:
  - type: category-1 (Bigquery)
    policy:
      id: gofin_iam_policy
      version: 7
    roles:
      - id: roles/bigquery.admin
        name: BigQuery Admin
      - id: roles/bigquery.dataEditor
        name: BigQuery Data Editor
      - id: roles/bigquery.dataOwner
        name: BigQuery Data Owner
  - type: category-2 (Custom)
    policy:
      id: gofin_iam_policy
      version: 7
    roles:
      - id: projects/integration/roles/project.iamManager
        name: Project Iam Role Manager
  - type: category-3 (Api gateway)
    policy:
      id: gofin_iam_policy
      version: 7
    roles:
      - id: roles/apigateway.admin
        name: ApiGateway Admin
      - id: roles/apigateway.viewer
        name: ApiGateway Viewer
      - id: roles/apigateway.viewer
        name: ApiGateway Viewer
```
        
User has to select the Category first (This will be taken from type field in resource list) and then the corresponding roles list inside that category can be populated for the access.

CC: @singhvikash11 @bsushmith

**Comment by rahmatrhd** [comment]
`provider.config.resources` is not for specifying list of resources the user can select. It's actually config for each resource type in the provider e.g. for bigquery there are `dataset` and `table`; metabase has `collection`, `database`, `table`, and `group`; and for gcp iam right now is `project` and `organization`. The config describes the policy applied to each resource type and the available roles. 

> Note: role can't be treated as a resource in guardian because for an access (appeal), it requires three main components which are `account_id`, `resource`, and `role`. So each resource and role serves a different purpose here.

the current implementation of gcloud_iam provider for the role list is by fetching all available roles from the gcp iam provider. for grouping multiple roles in gcp iam, here's some options that we can take
1.  (no changes required) **Create a custom gcp role that includes multiple gcp permissions.** This won't require any changes to current guardian since gcloud_iam provider also fetches custom roles from gcp iam.
  Note: https://github.com/odpf/guardian/issues/184 still can be applied to whitelist/blacklist certain roles
2. (require changes) **Map gcp roles into guardian roles** as how it is already in bigquery and other providers. In this case, https://github.com/odpf/guardian/issues/184 won't be necessary since we've whitelisted the roles as the following example
   ```yaml
   type: gcloud)_iam
   ...
   resources:
     - type: project
       policy:
         id: policy_id_abc
         version: 1
       roles:
         - id: category-1
           name: BigQuery
           permissions: # guardian permissions is list of gcp roles
           - roles/bigquery.admin
           - roles/bigquery.dataEditor
           - roles/bigquery.dataOwner
         - id: category-2
           name: Custom
           permissions:
           - projects/integration/roles/project.iamManager
         - id: category-3
           name: Api gateway
           permissions:
           - roles/apigateway.admin
           - roles/apigateway.viewer
   ```
