### ISSUE TITLE
Getting 3 times slack notification for same resource reminder

### ISSUE THREAD

**Issue by singhvikash11** [odpf/guardian#329]
**Description**
For the same resource expiration guardian send 3 times notification, I am guessing the reordering of var notifications can cause issues.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/61542640/202419709-cba843ed-c46f-4011-bec2-429b3798cd24.png">

**Comment by bsushmith** [comment]
This is a misconfiguration issue from the deployment side due to multiple configurations that need to be set to disable one job - 

In code, `JobConfig.Enabled` is set to [`true`](https://github.com/odpf/guardian/blob/main/internal/server/config.go#L23) by default (for backward compatibility)

and while checking for jobs that need to be enabled in the server, we check for [both](https://github.com/odpf/guardian/blob/main/internal/server/server.go#L245) access and grants jobs enabled for backward compatibility. 

This would necessitate disabling both if we want to run these jobs outside server as part of deployment. 


```yaml
JOBS:
  FETCH_RESOURCES:
    Enabled: false
    Interval: "*/1 * * * *"
  REVOKE_EXPIRED_ACCESS:
    Enabled: false
    Interval: "*/1 * * * *"
  REVOKE_EXPIRED_GRANTS:
    Enabled: false
  EXPIRING_ACCESS_NOTIFICATION:
    Enabled: false
    Interval: "*/1 * * * *"
  EXPIRING_GRANT_NOTIFICATION:
    Enabled: false
```


We should consider if we can deprecate these backward compatibilities and have only one config moving forward and have `JobConfig.Enabled` set to `false` by default.

@rahmatrhd @haveiss @mabdh
