### ISSUE TITLE
auto_approval not working as expected

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/guardian#94]
**Describe the bug**
```yaml
id: auto_approval
steps:
- name: auto_approval
  strategy: auto
  approve_if: 'true'
```
This auto approval policy which the steps are ended with one `strategy: auto` step, won't automatically resolve the appeal's status on appeal creation

**Expected behavior**
With that policy, the appeal should be automatically marked as approved on appeal creation
